ENG_PURPOSE = (
    "The end purpose is make a web service. "
    "Most of all, YOU MUST make a project directory to save all your results. "
    "The web page is about the Korean soccer player, Heung-min Son. "
    "Search who he is. "
    "Collect recent newses or information of him. "
    "And understand him well. "
    "And save the understanding as a text file in the project directory."
    "The background of the webpage is pastel skyblue. "
    "The Heung-min Son's picture is at the center of webpage. "
    "This picture is the Wikipia picture from Son's page: https://upload.wikimedia.org/wikipedia/commons/c/c1/Team_Korea_Russia_WorldCup_02_%28cropped%29.png. "
    "The short summarizations of the understanding file about him are under the picture. "
    "The links to go to recent three newses are under the short summarizations. "
    "The text layout is a center alignment with half length of screen. "
    "After all, Run it to get the webpage. "
    "Test the webpage is running well or not with terminal commands. It should not be '404 not found'."
    "Test saving and loading image with your server."
    "Use port 3000."
)
